

let l;

let mentors = {
    "records": [
        {
            "id": "recK7qq0Ovl5rN8qU",
            "fields": {
                "Name": "Anna Evgenova",
                "Username": "@Anna_Evgenova",
                "Calendly_Link": "calendly.com/anna-evgenova-nutritionist/45min",
                "Biography": "**Сильные направления Ани **💪:\n\n🌿Комфортное и стабильное снижение веса без вреда для здоровья и самочувствия\n\n🌿Разбирается и помогает с базовыми анализами, в том числе на микроэлементы\n\n🌿Здоровые отношения с едой и управление пищевыми зависимостями, в том числе от сладкого\n\n🌿Построение грамотной программы тренировок\n\n🌿Работа с терапевтическими протоколами питания (Палео, Аип, Кето, Антикандидный, lchf, Lowfoodmap, Кардиоплан).\n\n🌿 Помогаю бизнес-людям быть в ресурсном состоянии с помощью питания и нутрицевиков\n\n",
                "Photo": [
                    {
                        "id": "att00v0FtYmqtCoMu",
                        "url": "https://dl.airtable.com/.attachments/b9c29295b0cdf853d4523067e054f392/508ef8c8/video.mp4",
                        "filename": "video.mp4",
                        "size": 105013,
                        "type": "video/mp4"
                    }
                ],
                "Chats": [
                    "recMZfO66My6VqQji",
                    "recmbRD8AnwSXlqsU",
                    "recHx0bYhiPCvKrm2",
                    "rec0pcwUBJBr9Vtci",
                    "recSsDnrnBaHnGpWD",
                    "recweOkgqE5wPG70b",
                    "recJoF7ANo5ryHzqA",
                    "rec68LDRwIQby8XWB",
                    "recvI9BZbLnytoPtb",
                    "recsyfdkkQXUuFNYe",
                    "recvOqc6B68HpNDx3",
                    "recxgotpc7c3BU1Zj",
                    "recOTwEfqnyxA8QGY",
                    "recGTLg3yZ7cpO7md",
                    "recs8WWP3l3iJBNqg",
                    "recULVAPkUSjXxTny",
                    "recYqhvBhwk7zko9U",
                    "recIuIKdz88qs02Ol",
                    "rec8gsrdozS1LRYEi",
                    "recMtjGxbwlhhnLN8",
                    "rec6UvbJqd9WPDPn2",
                    "recaB3qFhhIVyopUH",
                    "recgw5Gj30pvNClJg",
                    "recc1w9TdN1KnykEX",
                    "recdWrhwa9f808FcF",
                    "recz5aSlBejQQ7V7Z",
                    "recGV9pk3yBlFD1f2",
                    "reclgWSHigtACfoL3",
                    "recA8KBzNCrH6lzbQ",
                    "reclnYMfTBcehKtkU",
                    "rec0iV695V2xxQvxx",
                    "rec3K1cZrd1x3gDsU",
                    "recW27AB6AQ66m3pS",
                    "recXiG9VmBM0l4umi",
                    "recGLu9RrUuKlzP4C",
                    "rec5HpPBUCYT6YWjg",
                    "recDnCxFggaa4cdSC",
                    "recwqHvDk7Y0twx3x",
                    "recPr10YhC9v5KufH",
                    "rec5dYv7I0AdpIH6h",
                    "recwwQ0D9eqXdbfRJ",
                    "rec1poCPOevu2Dc1y",
                    "recFRkKNewUHhn320",
                    "recIwyq4IphhrLIUf",
                    "recnSghTvRY0bkjAQ",
                    "recNRW4zS6CiAGcUn",
                    "rec9RY8z45KQB9sMs",
                    "reci3yKI3FvZY6nMr",
                    "recOooK0AAL4jHbiM",
                    "recEC5LzPIoJZ5TMX",
                    "recd9fBlwLMpRX7Fw",
                    "recF5zSXva03JPUqX",
                    "recuvSKEdzFONrsYf",
                    "rec5VGR0RG09Qa0RP",
                    "recO4mhxHPnCHaWRO",
                    "recHKnJ8YbtQtOq7o",
                    "recIv4sfRFi7LfPEk",
                    "receMfVaOpjFKbGrJ",
                    "recTjEHm34JQv5xEs",
                    "recQnrB2OUPcGmNBD",
                    "rec1Gf2bhv6S9RphS",
                    "recljEFna52inI5XZ",
                    "recgDvOuQsmGS9q9C",
                    "recPY9JX7XLALiFhv",
                    "recyeFDbJP0xm8iYf",
                    "recCvLSAgIRAq0PGG"
                ],
                "Displaying_Name": "Анна Евгенова",
                "Clients": [
                    "rec7cFalelwq0bXXo",
                    "recInk4WagME46Wyv",
                    "recysMDkaGxClNjlN",
                    "rec4VAM472ivd1AnQ",
                    "rec6EdONDNsjHOsDM",
                    "recw33szcx0BRQa41",
                    "rec6uvE9QkrHnoaMV",
                    "rec3TEQsT43TcMM07",
                    "recsAx7mk4fqmI4dX",
                    "recIawoGvoL3KuMYU",
                    "recQArGYEOdjRp0pE",
                    "recYATFFuAcImTNDD",
                    "recJTy4XDQccTosXM",
                    "recevz5swvLu8Cecd",
                    "rectP2hAAT7hXDpew",
                    "recSY0Y7h6N9JkTlU",
                    "rec4ane3PhFLaaB9l",
                    "recZ8BxM6rnck0598",
                    "recIIMo7FAPnDwjaT",
                    "recACoHzTqS9yTt6l",
                    "recnkIW0QeHTHr3b9",
                    "recsrwOT31v9VHlkg",
                    "recqzMrsMaAHT0Ksi",
                    "recqLPKlyZ2IzF9wX",
                    "rec2EwAcRrI8qnSZD",
                    "reclNdzuBfB3DicWD",
                    "recusikmlfHzxxjrU",
                    "recV2qFXygSQjVKr4",
                    "recUR7gu2idN2bQQz",
                    "recnzRCkRioGxWusw",
                    "recoJpGPSSWZQVGPY",
                    "recWy5C4Ym0HPXYJV",
                    "recJj8xes9S1WRnwJ",
                    "recAtMptqyGEeyYbr",
                    "reciCQQioU7sdOFDj",
                    "recD3VYsje9jF70gR",
                    "recQbeyRA8KezsX5P",
                    "recaCcnQwqr3xdr67",
                    "recUUvB0nD4XKaMsx",
                    "recY6UP9dHPKC22Mb",
                    "recCFK68OuUxU1sZY",
                    "recDR7WU1M8MTWCMw",
                    "recImWDBUXz95l2Ld",
                    "recqgC7C5pYjloo6Z",
                    "recKQ2cVqGaYypzsh",
                    "recSA0o96cTbsDEjn",
                    "recBCLDsOXAtErKv2",
                    "recJq0Jc6XBMDRgSY",
                    "recYiu8N5FoHghryC",
                    "recsX66U08YXeptii",
                    "reciTxJGUwo3aR33a",
                    "rec08a0rZ5cIUdbEV",
                    "recQfSkTc6qsQ1wmE",
                    "recIvaOcUDBjRM3Or",
                    "rec47VwHVDjFWri4w",
                    "recgYTowYqSk60482",
                    "rectqB8JQPZI4hsoj",
                    "recXLYZKJYPGj4SXi",
                    "recvQFgUYEZvoQjNy",
                    "recsWbhYyvxN8xU0e",
                    "recdF70uBO9rHDe2v",
                    "recXgHj4GjmLsysGS",
                    "recami47SoJ1bjf9R",
                    "reciU5GdXJ47xPJbU",
                    "recJjcpOyAjFNQ9VA",
                    "rec2BkfaNWbMcJkAr",
                    "recI1BcASIkXtQBTq",
                    "recWcOIP7g80A1wx9",
                    "reccPzcNsRwKTYPdG",
                    "rec5bh8N30iTnr6xZ",
                    "recw6xrBQaElFq6BW",
                    "rectuxySs9neMJCIA",
                    "recBcy5VScHzzw0wT",
                    "recrw25tRYOGGA91R",
                    "rec0AR9247zwcnu7u",
                    "recZMg0d55Vc85iBR",
                    "rec2j3a9WW14oiIu2",
                    "recjikV0FNzmtouRH",
                    "recY1QJo77xyXRy5t",
                    "recMp3px6kOlVAWOe",
                    "recmFOOqKCBsoF07F",
                    "reccvuRUboXDzLnFa",
                    "recy2kcxS7OnOFLi4",
                    "rechbPZaincd2BxVV",
                    "reci0ksH39z5ViG7h",
                    "recmJR3tB4cj8HhOu",
                    "recHJtJI3cwTSseWG",
                    "recj3FMcWjxnKk8Qy",
                    "recJphrh9dF4Q6sQW",
                    "recSZ29L3wgVN6dG3",
                    "recifvVPh9Sb3SL3v",
                    "rec2WzGbDiKNx9N40",
                    "recAYKBFGtl8i3RSw",
                    "recyYFoiEAf7VuaJZ",
                    "recLJjxJfFMSBoGvS",
                    "recoSOOdx25HnLm48",
                    "recUz6Bs1twY2sSk5",
                    "recRvprE5U1NGIiPD",
                    "recNlO881pNfQWcrl",
                    "recaMe5m04ulgsXFK",
                    "recaxb6eFpgKz6H1O",
                    "reclGlLkfeVFZ0VpC",
                    "recIFPB0vqqshG7st",
                    "rec0UaZgJtYBniqTt",
                    "rec74zUU7hFQ65aCx",
                    "recIp1IucprI6MNWC",
                    "recavQOFkUKfXCZPP",
                    "recjgdGKm8CATyq3L",
                    "recyjhCii4AwnLlsM",
                    "recRNpZtrXKu9M2zH",
                    "recJX1xstep4pEgkg",
                    "rec6iunqY0r87ilGI",
                    "recbkYCZGtClVxFnF",
                    "recf9CUUH6AyLqSUK",
                    "recPW5pHozhjIYxti",
                    "recBSfudmIlrI81fj",
                    "reciI2hKYwB4LX3F3",
                    "recaVaQJbg8I9rmFP",
                    "recXRRwrM1oSjtt4e",
                    "rec2xYSSPwK6Q3yc5",
                    "recTcMS1UG1IlHCz5",
                    "recx6h9KYZsZGgo1I",
                    "recb131p8NqzNUlAJ",
                    "rec1tjYROEIykPX7l",
                    "recz1egD981EGf2HA",
                    "reclG1bPWATccyPeF",
                    "recx1WGJ6IkHmTrwd",
                    "recqclEmd43vcA7W7",
                    "recjlRXkiEf1Dhneu",
                    "reciKg9V5mI9jFV3q",
                    "reckpWIu0PL4DaQPZ",
                    "recr4WJMptHWIqGus",
                    "recSsAGEq2samBSgO",
                    "rec2KOX48M4K6kHEd",
                    "recmi3LxtONpGXldq",
                    "recbaa9OC94grBmFl",
                    "recq4PNp9anIGVsvI",
                    "recMgm3L2TAnxCWfk",
                    "recj76lzggErA4Fkn",
                    "recAJlkO7yQCiwPqd",
                    "recTWDCoazSdxjHZq",
                    "recrwR8j76WOIfc96",
                    "recRCt6gr8qwF9VEH",
                    "recJ524DcS8w7pbBW",
                    "recfABLCO9AEBDDYP",
                    "reccGRNNwksZk048j",
                    "recdap0JvXkFilJAm",
                    "recq94aT4VBP05tht",
                    "recGKyqrhGtVs6hY1",
                    "recjUvBFuGhQq9Ft6",
                    "reczvTysKwoTI0XYO",
                    "recJixy561MAynlE0",
                    "recPBXLb1b5mzaEmO",
                    "recKSgVbsIwQavkDI",
                    "recMTyIVc6MYD4I6F",
                    "receSxjf7n00Y2GIj",
                    "rec6qQkJxSYkXzp79",
                    "rec852jHgZXxKEJKU",
                    "recrQEblOWxJNbhHO",
                    "recsl9rCDX6IevAiX",
                    "recEPemZDQox9iXjK",
                    "recBXSWqz3O4taXbn",
                    "rec7i4k3F28y4oRnu",
                    "recQY7Vd45SoaQePg",
                    "rec7scvFEN14i1Sf8",
                    "recGK4LZztrf56M2J",
                    "recIg2ETYRhIutCV5",
                    "recTawbKq34Jt0e6K",
                    "rec8idNKIoIZbZ4g7",
                    "receriDb1J7kySko8",
                    "reccYIwM8y6F1nn2P",
                    "recAlOgiEvz53OgGW",
                    "rec5r3PSx3w4MGVTD",
                    "rec2StgAgOXefOqVC",
                    "recnTijfaSOBZkqcv",
                    "rectxebIMwYjJaXvB",
                    "rec8UjwN2XUbjBogC",
                    "reci1DxUjtHhg3l17",
                    "recRyFrbDs15Oe6K1",
                    "recQ9YqVUY3gq6e2m",
                    "recQvnlWpytqu9GPh",
                    "recFtn1FzELsJGtzs",
                    "recJnaFeJecol93wg",
                    "recevfxY5y5iFsiaP",
                    "recuoDeMbuYdH0M2u",
                    "recYUbPul1zzRNzkv",
                    "recBtGEfxOeish1U2",
                    "recoHkORrh91ShNCf",
                    "recIC3niVFIELNN2Q",
                    "recAyU3yYjc0o6K71",
                    "recJKdDpqM2MXiXQ3",
                    "recxEdNPaEdztUuko",
                    "recj9TXC4WFkFFZQr",
                    "recBUgnsBNH50W833",
                    "reczQGAqw7vfblSYE",
                    "recpKRFE7bsdD60Eg",
                    "recVqpAD1x49d18TG",
                    "recgX3yLx2MjZXzj7",
                    "recch7OtNXXtYUiAe",
                    "recYGT1ZOYPAM25C9",
                    "rec4QXJNi0vxSkcCP",
                    "recenDx3oyMS0wzAR",
                    "reczLVC7GQZOuPI37",
                    "recttYB5KZhGJ8PvE",
                    "recCp1KtWapzOy518",
                    "recRJDJWWahkNQ3xK",
                    "recZqwBf7UvZ3jR7i",
                    "recY9v0wxjbdwuMv9",
                    "recEzcHfsBMPLsY79",
                    "recfukiste6xQBWzK",
                    "recKPUKvpCYL3HYNG",
                    "reciRUAbzgbEJEpjK",
                    "recWtpeUp8QusQPLa",
                    "rec5wJNSF832bzgWX",
                    "recB2tZKiCLHJQyfj",
                    "rectwB46P5gOv1ObD",
                    "rec9mPByEBJKlxGRH",
                    "recbetjChJuwHGg8S",
                    "recOdILXlGxmjYqPv",
                    "rec7Oug2dNo9z3zVA",
                    "recRN3gUpFgFKbTmk",
                    "recfHYPn9iMDhbuyW",
                    "recdbhjDNT2FVmQdx",
                    "rec27qbLK7m6FByy7",
                    "recbgU4fqCgC9p5oM",
                    "recHQXBhI0cgG6nWV",
                    "rec32ig7TVufSxM5w",
                    "recFl4wc5ZetjrGUr",
                    "recLUeFCZjSA0qDiu",
                    "recHZRUr0gRluLxw6",
                    "recZQd40uUxU7yppB",
                    "rec312HmktZHnCD0h",
                    "recKARggfUWOLTNgy",
                    "recdSnXozCHQ3VA6v",
                    "rec5QhvaWPdlbmPL8",
                    "recIwpwP5WqAw9R99",
                    "recP1ilWNomghJOHp",
                    "recqfSbHXbbEWhPbv",
                    "recMwQDK673izcCmI",
                    "recUPNOyEoI2URRuN",
                    "rec4oA5jhLsY9tr0F",
                    "recN41zK9DjbcPXiY",
                    "recklPbBsHl33mC3M",
                    "recdzCoLNUCtiDq4N",
                    "recor297VOfprspkq",
                    "reck4UhfeA0TdTM7O",
                    "recFu4nK8hJiLOese",
                    "rec4EFOccxS0LPKqo",
                    "reca8Dreb25ysD1nw",
                    "rechbTHsfdFWAxzsZ",
                    "rechT69r99BnRNkDj",
                    "recwi13Wr6ejrrGOI",
                    "recXJ16XHFdTcJdeV",
                    "recjz6YALuY2ut2gq",
                    "recatQzarom2bBFjf",
                    "recTcUhljhz979x8B",
                    "recaBkbzT4ITjq4S7",
                    "recWde0krMCrNNX2x",
                    "recPfYs4cCDjSnqgv",
                    "recvDBDayEDRtHj0v",
                    "rec0DZw8NALVJOf8P",
                    "recdB3p0KVmVyrnOE",
                    "rec0QulbuSc0mdA7W",
                    "reco23r0PrSOkgDCh",
                    "recvVq2ZUrDOFs5s4",
                    "rec9O4DRa9qbTNHRO",
                    "recwORgdmCHdSNqiT",
                    "recmfx8t6PPizuFK9",
                    "recDToySHVd9CUOmY",
                    "recRhyoWRrZTzopyg",
                    "recCFNMPNBki9eM4x",
                    "recYEWMb0SBYhnkzz",
                    "rec00FudQ2TbHaq9b",
                    "recMwx4Tqb9grD7iM",
                    "rec6xnIT3Nw32Vll8",
                    "rec08Ew0TGNgxBeqf",
                    "recEqk1Hwp5Go1N6m",
                    "reczSpc8gqmoJLR3A",
                    "recCpiOqLnNbCz61D",
                    "recsS7aar59ZAEwML",
                    "recFg9MSTgOd6HND3",
                    "recybqxA4iOOitRu3",
                    "recjtN1iHp9QCpFv6",
                    "rec4v89IHdiX9mQQv",
                    "recpe7650LtABYFdS",
                    "rec1okbXR82HVSox1",
                    "recj20NqWLXUf1Yes",
                    "rec44R4s0E0O7zziA",
                    "reczq5FkGl1177NHn"
                ],
                "Bot": 2,
                "Characteristic": [
                    "Мотивирующий",
                    "Структурированный"
                ],
                "Calendly": [
                    "recefF5hLhqf2m0GA",
                    "recxEbNppGfsfg8Kt",
                    "rec55GrnQBSnrSK2A",
                    "reco62HieFoLF1RBu",
                    "recdfT5ydoK7j4tDA",
                    "recg4lKkfLfD0MqGN",
                    "recs1ezmEujZzUga5",
                    "recFWYoxgoLXOgrQR",
                    "recDiv5vc5YNFkfVx",
                    "recEU3FUiqSPxNq10",
                    "reclygriKFxLogHkY",
                    "reczC7wTjPlOWlGEA",
                    "reccWKmtmpcPAG7Ac",
                    "recBHJtsOCpt6g2bC",
                    "recfRDvjeHX8DGFL9",
                    "recEoxKYV2kEcDnrW",
                    "recqSMc75h5lZ3OLN",
                    "recS61G6aw0n6yYXz",
                    "recWtetNoVw9z8Bfa",
                    "recsKUNRr0NpVZqFq",
                    "rec4sDXilJLJxmk16",
                    "recLhQ9GufdKYdMjD",
                    "recvp8U5IXrkXmc70",
                    "receJ8si7p0a255BY",
                    "reckILKeN25q0qlM2",
                    "recidu3D7PhMXYEQp",
                    "recShuiO68unsC9GN",
                    "recLump2nCc7u6OKE",
                    "rec5aj5U6RSAtWvvz"
                ],
                "Login": "annaevge",
                "Password": "annaevge",
                "Calendly_Link30": "https://calendly.com/anna-evgenova-nutritionist/45min",
                "Clients copy": [
                    "recW5cqGmHQbP2PKb",
                    "recmBlY4e4NL0cmxn",
                    "recGU4aS3WmfpsQGd",
                    "rec2gyCtQSldUQmoj",
                    "recUjZBgGU9E2ikLT",
                    "rec0D6LA6uCyxvaOs",
                    "recB8BlyjBcKLP6se",
                    "recbqr5mC4eMPU86X",
                    "recaXQRIGwwA6Fnng",
                    "rec9jxw610IT7nCxf",
                    "recKTqGbAeOyppaDI",
                    "recm6JhPwD6e12Yky",
                    "recqzgsG0JOMskly1",
                    "recMmyDPHZ8RRsiJP",
                    "recGlVEAOeh4Im656",
                    "recsxmnosx6tODOqP",
                    "recHEfAjDFg8aFW4q",
                    "rec1MjpXcgy5uPi5P",
                    "recYhN1tTIJzsAp71",
                    "recVUDqj1BKQjcW12",
                    "rec4EouTTREEHYxsg",
                    "recqxHbhb71Z9yFwB",
                    "recPIaii5XEk9SeBI",
                    "recQo76ogm975M2ST",
                    "rec7uL009jHvtXO4b",
                    "recLZmFtvuZEQ1vzY",
                    "rec2MfkOBCet87tSp",
                    "recIgiCVr5hD8NTTV",
                    "recTRtJEQI3fpQgfD",
                    "recV9TYeR3oIeHOpa",
                    "recE88nSWSvSXRie0",
                    "rectyeibiU6HAiEdF",
                    "recgihOfUCDAMUC6Z",
                    "recnyxevXWnBXOIwr",
                    "recPp0ijSaWrHKydr",
                    "recyTvotWE2IOLAos",
                    "recRu5D2udUE6Iq3s",
                    "recHWL0dDMIZrCaNI",
                    "recb2o3BTckCO4Q1c",
                    "rec8hxOoNDaXjHBzw",
                    "rec6msE4DbkAFhz1B",
                    "recOhGwX7cvN5TKu1",
                    "rec2Qm0yBv0x7vQr7",
                    "recGapVPJDWUeF5ni",
                    "recufnhzWmcHnFu3D",
                    "recS9zoc47DI8206n",
                    "rec6U9Anf3y5riXzR",
                    "recqsD5F3n9LG8NEv",
                    "recXjKPqLWJIrdYKn",
                    "recQO5z10p2fKzj1M",
                    "rece44XgkcXhRtTPh",
                    "reczKNxi2bVw8BMtC",
                    "recJ9XozKUHLUTbDs",
                    "reccjLqeQRIKsA5uH",
                    "recpbwQYgkIJmtK5A",
                    "recFz7qRuRHT8qYkW",
                    "recBrjNQIkaiavdsV",
                    "recIeML880m7M2IsN",
                    "recwI1cUSjcItM6hI",
                    "recNpdxd5NHn2BmlY",
                    "rec0F5Nf8oxD7VYs7",
                    "recfU5Fc3MpqAVFb5",
                    "recCVoW95Oquzuy6V",
                    "rec43a70IdGKfY49F",
                    "reco9GGo0LyHorf1D",
                    "recAASNKDb9OyBLOn",
                    "recd0Bm9Uiqsyy6I8",
                    "rec5nuQ5NyLfmnLCG",
                    "recC9U0upBSMi0svG",
                    "reco0CcN6zWCIMQXG",
                    "recktAwQFP5oHScgj",
                    "recnz9wiSgBht9P4b",
                    "recJQnMyOhQ3uESiG",
                    "rec2613fdue1U4pqe",
                    "recERBk83I1IMhgxG",
                    "rec3TKSp4AswkRYFc",
                    "recQiDV7yuyi7b03g",
                    "recFrcb7trVxWRd7w",
                    "rec6fvVbjcuJqYLjN",
                    "recfJDiUWIVjfl9Iy",
                    "recRzzvYXhXGtlGVE",
                    "recF7nSq80g3HhsHO",
                    "rec3AfJlL7jJXvaHj",
                    "recaF6owY2R1fnB3C",
                    "recmEzYiF7Jq6Xjw2",
                    "recKanCUcWqJKgOEO",
                    "rec8Rxb8r6dcNRpLE",
                    "recmwxSvh9sTKOooq",
                    "recZwRTOhAS4bY7Np",
                    "rec8ybRxKsdTAzMEv",
                    "recNFDAL9grQtpaIA",
                    "recvHClRKF9lXbvRM",
                    "rec8GLCaDetxIcZ46",
                    "reckatvIsQ3W6Ejyn",
                    "rec9yXCtM8hYBtHG8",
                    "recc75jpnPGfm06F2",
                    "recGqjizJwVaVEbw6",
                    "rec7ebPjdiVdCpOye",
                    "recbDQS02HOnU6fhR",
                    "recqVXAAMA4b79Df7",
                    "rec8ytTHDLgAlohTX",
                    "recWMxOySmerdBgQX",
                    "reckPZ3vRjIDl6rss",
                    "recjPlUyg8xJnQBQu",
                    "recCIJKLt2TyqDbql",
                    "recZUskEVaamZYJf6",
                    "recwaN9Y57FPtlAtg",
                    "rec1zKdTHoLO72HKa",
                    "recMMW2v0GvBYmqg5",
                    "recKY1ZjKQNnd0k5q",
                    "rece0yY2IUL996jHD",
                    "recn6Dl9jxsyiQRAA",
                    "recqls9ajWL0hLiO5",
                    "recqwghnXONJoksox",
                    "recI9IcCfNJdoV1ej",
                    "rec3svhiMVTBWvk4w",
                    "recTlMVdYDZA9WKg3",
                    "recSstzyf7GSBf5v7",
                    "recqCPiiiyBstAbe4",
                    "rec8X9sYawZHFNLLd",
                    "receiZLOQ7vAHAIlG",
                    "recLwTxYtVHeLqHpV",
                    "recbcLRRpJe82Ncnu",
                    "recmS0Zfm4xWZ7xKY",
                    "recHuyLWYIyRPNfxx",
                    "recsvV5cV8uIRCIql",
                    "recujKIdJAXfJEyeM",
                    "recgKEp84473K7VaJ",
                    "recEEOWC8zsUGvv1P",
                    "recjzzw4sQnGIpj61",
                    "recFxFPyGPxXMsvwA",
                    "recDxlTNWpvksUOnb",
                    "recFzbRsQF5EAhHig",
                    "rec6MUZ2UdnyUCX0c",
                    "recNJFXBnmWRGQq7E",
                    "recIMBNDYpb61DQ2n",
                    "recngq46dahj1MW3b",
                    "rec4YdmZQadde2mG2",
                    "recp2loIePXWoOhcA",
                    "reca9TzCzmm7giexz",
                    "recDw76eM2BMzz2Xh",
                    "reck8qT7OhDLZj0AO",
                    "recf0r6iRJwxU0DhY",
                    "recrBqTEJiz06kIYQ",
                    "rec12zIiJNZuZLKrw",
                    "rec8Mo5etssg8lYTH",
                    "recB7xDYAC3Mv7kTn",
                    "rec0jMuHQ43MLrhOZ",
                    "recUBfP6eIW6ytIJL",
                    "recp7cbAhwWcayLLV",
                    "rec0mXaVsIJF93MJ8",
                    "reckhX5WClaymn3Ub",
                    "recNr1m4DfQChTwa8",
                    "recXtFYFjQzYIPZqM",
                    "rec0LrlI2JUimVk3K",
                    "recPVQ2z9aAAF02oH",
                    "recXqA5WAtlFd3fFq",
                    "recTdfYVrzfrwmUni",
                    "recajNAj4qXj94Jbv",
                    "recXcWP3TNvtQjoT9",
                    "rec7vMFwUy9QGU7pu",
                    "rec4XKZvvVK0F6r9m",
                    "rec8hvNXKdLW6Q0TM",
                    "recIVQlNxCNzSQQYp",
                    "recyZNOKUJE5MwpYw",
                    "recMCwfhTpWCnmhR6",
                    "recalYJAdtvVhAu6a",
                    "recPUZuuqGq5e6jM7",
                    "recqjvu8RLJbub3dm",
                    "recgj9tsc8YxxZl5S",
                    "recYTtToVR8shTzYp",
                    "recSVds477Z4rY2wH",
                    "recA859esHf6A1KCO",
                    "recq7GO8ZZzzynXDD",
                    "reczVZfctUmkbcru0",
                    "reclZXjNeZ7bVib3x",
                    "recqaPQtnBsIUo0gJ",
                    "recYdqPyTPuKzz2vC",
                    "recXQWk7h6IX1Q8ed",
                    "recqM0L1DUPXKczFe",
                    "rec7kOrqWGAULQRRL",
                    "recWKQCsPnGm8kuj0",
                    "recCrxBCP7nC0BwpM",
                    "recDmeMPFzC18iTlk",
                    "recrlXzLXkbwxnp5m",
                    "recXYXlkY1tyjsjYo",
                    "recB6hJ5kS8aLCdZ7",
                    "reczL8SQZ6gcegVwD",
                    "recPbZIo6Rb1oWPY6",
                    "rec60Xk13zGYBYJYk",
                    "recNQX6WsDjAYSzsr",
                    "rec9gkWy1gnNp68PG",
                    "recxWeHIxoS9BIk8C",
                    "receG19a5D9EtyABt",
                    "reciG47EYqvHhqFoz",
                    "rec16MLFZxzxtNVtE",
                    "receKPG9KlXOhCPl8",
                    "rec0W7Hbpr2Hg0lt9",
                    "recKfCnfrdoqLPcIt",
                    "recIgZXA49TgNR8VZ",
                    "recc37VsGSN0UVPNG",
                    "recG7GmrSfxqcBssn",
                    "rec2Qa9NqAEZFMujG",
                    "recPzSK04hPIM06eV",
                    "recEdDyZ6hIg1YX39",
                    "recYaoBM7i9EDTvD0",
                    "recc05JLhHDZWFsTm",
                    "recvbgqEUbZzyMl7H",
                    "recmChwfyO2O6TLd6",
                    "recd88Mm037Kh5Rxw",
                    "rec4gdI2lDLbcN11u",
                    "recQBvrqovio5r20h",
                    "recFokntsQoIpF0HA",
                    "recdQmTRa8kawrsYb"
                ],
                "Count Clients": 33,
                "Enable": 1,
                "Capacity": 50
            },
            "createdTime": "2021-02-15T08:44:38.000Z"
        },
        {
            "id": "reccRyOJE44z3MuH1",
            "fields": {
                "Name": "Anna Uvarova",
                "Username": "@anab02",
                "Calendly_Link": "calendly.com/zhelaydelay/45min",
                "Biography": "Сильные стороны Ани💪:\n\n🌿Работает с низкой энергией - выгорание, усталость, прокрастинация, дисбаланс микроэлементов\n\n🌿Фокусируется на создании долговременных привычек, без режима \"подвиг-откат\"\n\n🌿Поддерживает комплексный подход. Кроме питания важно достижение целей, управление временем и прокрастинация, сон и движение.\n\n🌿Используется экспериментальный подход. В теме здоровья есть много общих закономерностей, но и много индивидуальности. Она не сторонник одного образа жизни - разным людям подходят совершенно разные образы жизни.\n\n🌿Решает проблемы эмоционального переедания\n\n\n",
                "Photo": [
                    {
                        "id": "attk1gg4eekpvbbDp",
                        "url": "https://dl.airtable.com/.attachments/8c27ddb4a67014178e925eb99860327a/8cab72e4.mp4",
                        "filename": "Анна Аварова.mp4",
                        "size": 121012,
                        "type": "video/mp4"
                    }
                ],
                "Chats": [
                    "recWZveLBAOYnlXu0",
                    "recr2lGt3TMiSldue",
                    "recr8g7dJNtLWCU4U",
                    "recuQx3gjcnE0JGmt",
                    "recUeEjEhMAryMBII",
                    "recrm6nwxmHcMCRRO",
                    "recWSobBAQLyH4hNv",
                    "recaIYXk4nj9ntFDr",
                    "recoyEZYwWX4scpoV",
                    "recMfHnseQBlbFWxS",
                    "recWk6ehCxk1upvFW",
                    "recVvMBPguaMCipNG",
                    "recKtNzYyfaUKYe59",
                    "rec6qqeV7g1V8Orxg",
                    "recGl5HLApF3IPb8E",
                    "recVxUSLkGUdPkfgp",
                    "recboFM3oiOeneinK",
                    "recefL3tscPVcVqyo",
                    "recoeVRep3wfQc0vE",
                    "recDPwzVL4H1Ua8TO",
                    "recFLao02dK3vYyE2",
                    "recN18E3QNxWfpueB",
                    "recVk0rGShxo39IXD",
                    "recmkmOrV7PXJcGyJ",
                    "recP6NHA9AB5LlFHX"
                ],
                "Displaying_Name": "Анна Уварова",
                "Clients": [
                    "reccdFmeQyK9I53o1",
                    "recJmR7Drhm4Zpx35",
                    "recW1XiLOiMl0Ipmq",
                    "recdkglMaRDC7pB7R",
                    "recX1t3uOdOwkV7DQ",
                    "rechel9NHjOtgGzvc",
                    "rec4rrmxzeaDz9hIp",
                    "rec191gDg7YI5hylx",
                    "rec50VA4jQuAbo5XX",
                    "rec3uqVDdtfr3KoMs",
                    "rec72j6Iux4VJf97R",
                    "recLbW2EkZlRJcg8y",
                    "recJaUMQCWhO6YD6D",
                    "recwp9iB48ku2fqol",
                    "recgCcaxFUAikw9QM",
                    "recQhJMfCrTzjTlsv",
                    "rec2I7utIUSw0TD7I",
                    "recswWFfqFfKW7QAn",
                    "rec1RuKZg3qdsJHNj",
                    "rec2NgcbSlRqnakO7",
                    "recQENU4erTeHzNsV",
                    "recHAZJ987slHXKSO",
                    "rec4EmxSxKQJc4fbr",
                    "recmm3HrMlx1L2nzr",
                    "recZOZrTTle8LZeBM",
                    "recZDjZODv1uCsIAy",
                    "recYWAVF4ssCNpvqs",
                    "recaKCMbvfv6UMvSP",
                    "recVODWIWDQGJHni0",
                    "recxbDidmsagadjgY",
                    "recKOCacsh16FjPqZ",
                    "recVXAGHSHuj9crRh",
                    "recmQojxD00QMm4Ea",
                    "recKTU114znS9omBw",
                    "recHpNS4302M8FU4S",
                    "receuro8TjT9m3Gff",
                    "recTnahAKR4EJklHO",
                    "recj5vAvm4yrbqu2a",
                    "recGAHtRCgUYX2nms",
                    "recjdSpk62dmdYLNF",
                    "recR9kEJkI0M8M4s3",
                    "recmr8uVZnKp9nTz3",
                    "rec65PE84uzG8275n",
                    "recr8Z4dQDmldXP38",
                    "reci3hOqkEzakvhov",
                    "reckKU2Jc3ppmyMXX",
                    "reczYtXSLoGwrE3DH",
                    "recqopvesaGnILLbA",
                    "reclnnIzWEkQvEEjs",
                    "recVOF7N1imzE8P3O",
                    "rec1fY8sbI6kj94Vg",
                    "recG8aGbSUBk72Pwf",
                    "recRAT6mLvuxhqBlt",
                    "recFJ9BppoPWGTBjf",
                    "recEEumCeWPBiC56n",
                    "reczfM13pe32cQavd",
                    "recDRrITKLhxKG34U",
                    "rec0lTguCt7LtdXn4",
                    "rec8YQX6oHGB4ffLR",
                    "recfy5C68KlItZ3VN",
                    "rec1o65XfomBWlJ1n",
                    "reccf4y5zbaFJPyp0",
                    "recHQZUTpsK7d9z57",
                    "recIYKnAStw6UCvmW",
                    "recRY0vRjBNaxlF33",
                    "recdH1YhyJrskETyw",
                    "rec9FwEiC42rp0wk2",
                    "recFyDpUBQ8AUMfyz",
                    "recf0xz0j9gOTTgrT",
                    "recDnPO7lJDU0INwZ",
                    "recsznh7mdcjgsxWg",
                    "recUS53nsjpBcTJhP",
                    "recAkVx3Vhd4Q1hJ4",
                    "recaAVgCR10EEEtqI",
                    "rec1UTPGiSmHbOA4K",
                    "recz5A62dcAAU943a",
                    "recs8YhfRJoiUiokH",
                    "recfXHKWyXrCf4fQl",
                    "rec9YU5WwagzmUGW8",
                    "recVcuwz3s8cUC6cg",
                    "recRB5NCoLnckn7K6"
                ],
                "Bot": 4,
                "Characteristic": [
                    "Структурированный",
                    "Мотивирующий"
                ],
                "Calendly": [
                    "reccBXES2FHQ3CelB",
                    "recaHI29BWuD9RGoh",
                    "receMtWyyLAHCnXMt",
                    "rec2UY8mxs3rC3wTj",
                    "rec0LCIBC1ChH5NqD",
                    "recFk8OdCbrx5flky",
                    "recX9oWKTKXx8G5ZX",
                    "recQaxRPkMZlDVrzo",
                    "recGIhdbhvrbhVyyX",
                    "recMI9RsYiCU3hzhA",
                    "recWM2s2SsK5XjOaR",
                    "recoMArnUak86KGhi",
                    "rec6ysZfgBtmaKOJT",
                    "recxintEE43DCDbxW",
                    "recIgLD4uvmfZFBjq",
                    "recR3S9eTaucNnarr",
                    "recICBW6Xu6nkm5Pa",
                    "recNOYX1N07sInM16",
                    "rec5YXwlx1lNWwp83",
                    "recDQX0cjf8K9zVRX",
                    "rec2fIBqJSvrZ4pQ6",
                    "recbFrcon0YFFqCBp",
                    "recMQKTj1Do3OqhT7",
                    "recEfT2d8Gy6VQv0I",
                    "recEkVEXDC4FgSbmm",
                    "recHlNji890PQClYh"
                ],
                "Login": "annauva",
                "Password": "annauva",
                "Capacity": 10,
                "Calendly_Link30": "https://calendly.com/zhelaydelay/45min",
                "Clients copy": [
                    "recU8mtrQLilusahF",
                    "recLSee2bGHu98YSB",
                    "rec7TYtBrV2nOZqFS",
                    "rec36x5O9XiledUqF",
                    "recA56LgbPRi56U9H",
                    "recq1d8wjE1eoOXQ5",
                    "rectGbVSUzqvhJ5Lf",
                    "recm556IxkOt3PRKg",
                    "recjQJcEEuW2tzXN5",
                    "rec914T4s1VB47KbH",
                    "rec6RVCD499Tnea8C",
                    "rect9lzELxVRcAVEj",
                    "reclcgCSW0aErEQJp",
                    "rec3p8iWJZfdo5rvW",
                    "recvv2egPq4sAPQ9Z",
                    "recI8W57s7S9tSVkp",
                    "recJbz8ovbN0RLmZc",
                    "recIxvFPHMRehzqcx",
                    "recm4l5iVmgwNXT6e",
                    "recS6yzZvLfe32cIY",
                    "rectRPjdzrXM880ox",
                    "reclcWRK2s2KykMWi",
                    "recvxgRnLplQVx1bL",
                    "recZiiHn1uBlrBHNj",
                    "recxL1LfRX3XSJPrX",
                    "recKCduDNl2YjkjEA",
                    "rec97VX9kjzapGKmf",
                    "recryMpOepSjqJ6Nq",
                    "reczsZfyE0WWHz7HA",
                    "recbfVu08ySf0fQkV",
                    "recGzBNCQYlJDaEzo",
                    "receiwR6hD67AxzGq",
                    "recXMouBkGtoKU1C6",
                    "reciwE0wkf6dfO09o",
                    "recdp28hq339xIUHQ",
                    "recMGsxG4kCPYXJHv",
                    "recafIxtOsm4cm4Th",
                    "rec6uld3hUyFLEE0r",
                    "recHoIPczj3pbIBvG",
                    "rec5njqeUTHfZfwkE",
                    "recqpMz558eWy1puH",
                    "recqtbOOlS7fOsTMx",
                    "reccem4Imk4SokhMY",
                    "recT1wEHgJzlN2o8L",
                    "recdKQ73ZFg8q1D9P",
                    "rec26c0ELpmMJC7PA",
                    "recDMgZoU2dfmmVBD",
                    "recYtvyuuw2D76Thd",
                    "recHVV2cZUxFO55VI",
                    "recxlFSGDd706DQHU",
                    "recnfXYQ9pEse21J6",
                    "recyd7zj6FX7w296M",
                    "recPhmkSs0Esi8sIE",
                    "recNFecs1ed29TPwW",
                    "recdDPpccOQfrAsu4",
                    "recpUEqKdb7fo95z6",
                    "recaz3FoH8FBcsqAJ",
                    "rec39S8GYbHyGvO3Y",
                    "recdBGOtS8RKkqsoi",
                    "recNu3xD6vPfRB5FH",
                    "recO6WSIYITV4SlyB",
                    "recw3twfoIvR0RQIF",
                    "recJOYHIlpSvaIJo6",
                    "rec3iwLsflXVmOQet",
                    "recJN6Ck2HtdH48rW",
                    "recfBKDkM3ebaxmEl",
                    "recZKDYIRR9EuiSWH",
                    "recnEdxcI5HvP6rAQ",
                    "reclsZ8EcK0EC0SlI",
                    "recvr909pCSwKNV77",
                    "recvHwwsfcPXOqvfK",
                    "recgSmZnFeb9T9NC1",
                    "recThJUE6rlIa13ed",
                    "recU1hHMXr4sosDuT",
                    "recVagEqiKkNZ751l",
                    "recSkaV8xvldQe2Zl",
                    "recNoWYgnPFu90GGa",
                    "recw0sglKY8wmVPa2"
                ],
                "Count Clients": 10,
                "Enable": 0
            },
            "createdTime": "2021-02-15T08:44:38.000Z"
        },
        {
            "id": "reczIkcbTYM053E6k",
            "fields": {
                "Name": "Olga Amelina",
                "Username": "@olyaamelina",
                "Calendly_Link": "calendly.com/olya_amelina/45min",
                "Biography": "Сильные стороны Оли 💪:\n\n🌿 Помогает научиться слушать своё тело, понимать сигналы и их причины (голод, сытость, грусть, радость, усталость и тд), чтобы скорректировать пищевые привычки, включая эмоциональное переедание, перекусы, беспричинные изменения настроения и отсутсвие энергии.\n\n🌿Помогает встроить полезные привычки в образ жизни, учитывая уникальный опыт, навыки и цели каждого клиента. Это позволяет сохранить изменения на многие годы вперёд.\n\n🌿Помогает научиться 100% восстанавливаться (физически и ментально) как вовремя ночного сна, так и вне его.\n\n🌿Помогает подобрать тип физической нагрузки, который приносит удовольствие и наибольшую пользу для организма (кардио, силовые тренировки и тд); встроить тренировки в ритм жизни клиента так, чтобы другое сферы не только не пострадали, но и выиграли от этого.\n\n",
                "Photo": [
                    {
                        "id": "atttYKVhsCXQTwbM7",
                        "url": "https://dl.airtable.com/.attachments/d5f6d314abd3f1d3a3e30cd3ea4732fc/8eaaa24a/amelina.mp4",
                        "filename": "amelina.mp4",
                        "size": 79312,
                        "type": "video/mp4"
                    }
                ],
                "Chats": [
                    "recrlVQAKbtdEEZUW",
                    "reccSXaCbbsC45UsJ",
                    "recCvQOIsAOL7YEPq",
                    "recmgkNwQjcKcEL2q",
                    "reccVeZzFkJrGQIm6",
                    "recFU5IaVnldBGvZq",
                    "reccc2XDyeTCezLdM",
                    "recQKcCBvQh2t6UuI",
                    "rec0tvOM2yg8zWX4U",
                    "recc5D0rGA7ackR9S",
                    "recrLnEznWPUFysPH",
                    "rec7NzUH9D0pYiwJE",
                    "reck3j0VWBhMynO5g",
                    "rec4gogqQL1APKWhc"
                ],
                "Displaying_Name": "Ольга Амелина",
                "Clients": [
                    "recW6j2oLfhNz16op",
                    "rec0Eobyvx1b2pfAM",
                    "recdE3FgTq4byzQSw",
                    "rec8aPMWqNV32rkdY",
                    "recWPIHTXWMeX2Fzj",
                    "reciP8oItR9FvYWtG",
                    "reclroZANHtraL14k",
                    "recPD5GaANmsSSute",
                    "recYNFqTJ1LU95oYr",
                    "recHzmFbsILG0WiZo",
                    "recD0ZKNMTIA0nXP5",
                    "rec4os3tvGhENzuRD",
                    "recgV7YGNPefVVpIg",
                    "recYTv8q52zuYJDYI",
                    "recZ95HXp3p11cMno",
                    "recBcIdXa8T8YaPfK",
                    "recIkMFXI0mhPVWp6",
                    "recRxmZN1zCJu6ogG",
                    "rechdhQZGdOdgO5PP",
                    "recbLIVPlDGrU5o4X",
                    "rec1xThAAroqUVoT1",
                    "recNRI07ECLqryq4C",
                    "recqB049V6SEFh7ft",
                    "recu5F6XC00hxelZ6",
                    "recXrsC0gy4N5apKQ",
                    "rec4hqkZpEkSyRW6M",
                    "rec00CiMMX3lDsN5S",
                    "recxLu9beu80jn4oH",
                    "recfzbq5Xv8a2JDMz",
                    "recpbJOiNuwhKwgwe",
                    "recul7bA0X7zsZW88",
                    "recdNQIU9WA8V8TML",
                    "rec1G74x5OxHiVHmn",
                    "recP5nu41neaZ7XGG",
                    "recFiM5TUYy7Y3gRd",
                    "rec0DfhdX0oezxoEJ",
                    "recCLaRV9xQkwf0mz",
                    "rectWK16faPO15INw",
                    "recMMhaaloC3kYAAW",
                    "reczcmj8UUmvpZuqg",
                    "rec17pYof81u30UsA",
                    "reca8mo93GXdhX12v",
                    "recYrsJqCSEoZMUF0",
                    "recqrRuW8Q9AjgFBi",
                    "rectDjh8IDMC50Jr5",
                    "recqzgrPdv3RYYH5D",
                    "reczkayPHJu9v51SK",
                    "recyoDHx9f4sSUFUa",
                    "recHrpbRFTGxdHtZe",
                    "recfwGWybdxJU7w7S",
                    "recOz3czyXgABp51b",
                    "recbfkgSKTBEHGmNS",
                    "rec6EgNSuBeICSz7V",
                    "reczbifG2u24tDmrA",
                    "recKpSUThBejXcXiR",
                    "recac9mPCMScG9uGm",
                    "recDiHAvJ9UGgRwYy",
                    "rec1SRN99rfPI7dGP",
                    "rec9EoC2pUqm6hQsG",
                    "recd9fXwJRX2gzOyA",
                    "recHUUlERmVPfXo7t",
                    "recIx6JN1rxJ8dE4R",
                    "recAzj0nx0Ju4W0iQ",
                    "rec111Aze7crOzSAx",
                    "recObUQ9RR7NrXofr",
                    "recLMM1ydNH2rYQ7r",
                    "recHUoVJZbdmWSKSa",
                    "recgqdxoLwT8SbN0i",
                    "recpx1xxs9L2N9CSY",
                    "rec4lsV5jRN7U5SbO",
                    "rec99alSaQNaVBHyC",
                    "recFwYd1GGsVXaTvV",
                    "rec0ECbuCalMDnlHU",
                    "recFPQd6PQCXD8Srb",
                    "recynvPQqI7HguLPi",
                    "recczzWhOxgyT5UYs",
                    "reccj4EyLC8hmYE2s",
                    "recBWzmj5h8YNnmdC",
                    "recy4tOQOS49sDiH2",
                    "recN3vPbZn3djxTdY",
                    "recOxy9vygaMnKqRX",
                    "rec3gRTGyhPDikzls",
                    "reccvBkhGjIQ8BGup",
                    "rec8ULWL5IHpSU6Wr",
                    "rec9B9XqBIJZqoFxV",
                    "recTirCmgUSKKiXnr",
                    "recfHpdQpkG19A2OD",
                    "recJtSZ8p2mj3oX0P",
                    "recDUoXRTHhaHHwsz",
                    "rec2qIh0mh3idJ72J",
                    "recXCZxtLNCwQaeas",
                    "recTrWXNWVZ2okd8z",
                    "recgDMoZxrA3X0CRi",
                    "recCWfHrdwriaEiBP",
                    "recyOlsrLNmeewfqx",
                    "recvgqRDzjDSZ3yYl",
                    "recLVrmar4iGxnwvC"
                ],
                "Bot": 1,
                "Characteristic": [
                    "Эмпатичный",
                    "Дружеский"
                ],
                "Calendly": [
                    "recXCk75qb72YzOjP",
                    "rec2ecEedKWriwOY9",
                    "recjUbHm1ZlupGkC1",
                    "recPjl6lXGaB9gsjG",
                    "rechq5AgmiAopAvD9",
                    "recMBLIx5BypXI0Yx",
                    "recikXkxE1iBcBsOK",
                    "rectZ9FnRJG11GTO2",
                    "recqWRkPvmje6zzFN",
                    "recuQY1GZ3JyH6k3c",
                    "recofe6vPeaCVTALB",
                    "recDTpDz8PkV40Rwk",
                    "recD9IfAaPw43vzAB"
                ],
                "Login": "olgaame",
                "Password": "olgaame",
                "Capacity": 15,
                "Calendly_Link30": "https://calendly.com/olya_amelina/45min",
                "Clients copy": [
                    "recN9icXFPuXv9vJ5",
                    "recfEK21NBQ85tIjJ",
                    "recIBC5XxcVHDkXhX",
                    "rec50QwJFGUJ7CB2R",
                    "recpAXkD6h73jjvty",
                    "recHGcsxLzXv8GXAN",
                    "reczgn8Jhq4kc1ZWG",
                    "recez04wGPl3mFGcB",
                    "recdELBxSvFRdJ1by",
                    "rec8bI29C061QDmb3",
                    "recwkFVvkObmquPem",
                    "recPQ7cSz4lYHVFyu",
                    "recRaqFCb5SOF5P87",
                    "recKJ5pS6gcOwqmbR",
                    "recp3Tbg06xJiTWj7",
                    "recdEqeqNLAKEcQtt",
                    "rechw1S79GcGzDCKi",
                    "rec2f90VA7iy5Cgwp",
                    "recg04OHGromjFQpp",
                    "recc5b9YMkhwOwAwn",
                    "reciT9uCkwSfsJngw",
                    "rec3K3pUeQRYTVoZY",
                    "recvEAQINEdaTuOpE",
                    "recXWvSEdHxiDzVHK",
                    "rec4X6gr15lgvpJkd",
                    "recOX0ex2mOcbnFcF",
                    "recbTEdqJyO2wJcJg",
                    "rec7rwDRTKREkJLAk",
                    "recUbXesJQrOSBYj0",
                    "recdxdTo9Dsv4a19P",
                    "rec2dI6u0Uqc12GNF",
                    "receJuPZQCnl9TNEd",
                    "recRyGeoCQVTK8QaD",
                    "recnZ0h5wHvUoNZuA",
                    "recc8vNB9AsMj8NXB",
                    "rec3Jdkh4FuCtjk19",
                    "recDf2SmiUJ8j0Has",
                    "recope9Y1zRufGoQv",
                    "reccTUJgdf7WBVPk7",
                    "rec2jtmIBQYw7dxl2",
                    "recT4tcpFR7UZXemZ",
                    "recmpZ61L9aZKZbh4",
                    "recEuuJSq8muuSvLp",
                    "rec0L7xw4TiinLub8",
                    "recKf2FKQBt7YSraJ",
                    "recu2lPl6h0icXYa7",
                    "recCbyefgTzBpAYh9",
                    "rec6kYFQGThImyhJV"
                ],
                "Count Clients": 9,
                "Enable": 1
            },
            "createdTime": "2021-02-15T08:47:14.000Z"
        }
    ]
};

// mentors.records.forEach((mentor)=>{console.log(mentor)});
// mentors.records.forEach((mentor)=>{console.log(mentor.fields.Characteristic)});

//  let res = mentors.records.forEach((mentor) => { 
//     mentor.fields.Characteristic.filter((i)=>{
//         i == "Мотивирующий"}) 
//     });
// console.log(res);
// let res;
// res = mentors.records.filter((mentor)=>{
//      return mentor.fields.Characteristic[0] === "Мотивирующий";
// });
// console.log(res);


let res = [];
// let pointsMentor = ["Мотивирующий", "Структурированный"];
let pointsMentor = "Мотивирующий";
function getMentors() { }

mentors.records.forEach((mentor) => {
    let characteristics = mentor.fields.Characteristic;

    if (Array.isArray(pointsMentor) && pointsMentor.length > 1) {
        pointsMentor.find((point) => {
            characteristics.find((charact) => {
                if(point === charact){
                    return res.push(Object.assign({},mentor.id, mentor.fields.Calendly_Link30));
                }
            });
            return point;
        });
    } else {
        characteristics.forEach((charact) => {
            if (charact === pointsMentor) {
                 return res.push(Object.assign({},{id : mentor.id, link: mentor.fields.Calendly_Link30}));
             }
         });
    }


    
});

const random = Math.floor(Math.random() * res.length);
console.log(random, res[random]);

console.log(res[random]);
console.log(res);